---
# vars file for xrdp

# SSH service name
_service_name:
  default: xrdp
  Debian: xrdp
  Ubuntu: xrdp

service_name: "{{ _service_name[ansible_distribution] | default(_service_name['default']) }}"

# Packages to install
_packages:
  all:
    - xrdp
    - tigervnc
  CentOS:
    - xrdp
    - tigervnc

packages: "{{ _packages['all'] + ( _packages[ansible_distribution] | default([]) ) }}"
